### ISSUE TITLE
require esm issue

### ISSUE THREAD

**Issue by bernaferrari** [JacksonKearl/gjp-4-gpt#1]
I've been getting the following issue in NodeJS which makes it impossible to use your library:

```
const gjp_4_gpt_1 = require("gjp-4-gpt");

 Error [ERR_REQUIRE_ESM]: require() of ES Module 
.../node_modules/gjp-4-gpt/dist/index.js from ..currentFile.js not supported.

Instead change the require of index.js in ..currentFile.js to a dynamic import() which is available in all CommonJS modules.
at Object.<anonymous> (..currentFile.js:52:21) {
code: 'ERR_REQUIRE_ESM'
}
```

**Comment by JacksonKearl** [comment]
Thanks for the report. This package uses ESM bundling, which from what I can tell is the modern way to bundle that many popular packages have switched to entirely https://codingbeautydev.com/blog/require-of-es-modules-is-not-supported/.

Is it possible for you to change your application to be a module `"type": "module"` in `package.json`, then import as `import * as gjp_4_gpt from "gjp-4-gpt"`? Alternatively, you can use the async `import` function without modifying your `package.json`: 
```ts
import("gjp-4-gpt").then((gjp_4_gpt) => {
  console.log(gjp_4_gpt)
})
```


If this isn't an option I can look into supportting both ESM and CJS bundling.

**Comment by bernaferrari** [comment]
Tô be honest, I'm not familiar with them, I just couldn't use because of the exception. I'll try here. Thanks!!
